[project]
name = "archival-structures"
version = "0.1.0"
description = "A Python package for analysing and restructuring the output of Automatic Text Recognition (ATR) pipelines."
authors = [
    {name = "Marijn Koolen",email = "marijn.koolen@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    # "pagexml-tools @ file:///Users/marijnkoolen/Code/Huygens/pagexml-tools",
    "pagexml-tools (>=0.8.0, <1.0.0)",
    "numpy (>=2.3.5,<3.0.0)",
    "lxml (>=5.3.0,<7.0.0)",
    "fuzzy-search (>=2.5.0,<3.0.0)",
    "pandas (>=2.3.3,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
pagexml-tools = {develop = true}
